

if (settings.easter_egg_cards.value()) {
  var bonusExtensions = ["DDLC", "LUNA"];
  var bonusTribes = ["CHIBI", "DOKI", "CHRSPELL", "MELISSAATTACK"];

  GM_addStyle(".cardImage {background-size:contain!important; background-position: center!important;}");
  GM_addStyle(".cardRarity {background-size:contain!important; background-position: center!important;}")

  for (var i=0; i < bonusExtensions.length; i++) {
    var ext = bonusExtensions[i];
    GM_addStyle(".monster.ext_"+ ext +" .cardFrame {background-image: url('https://raw.githubusercontent.com/elytrafae/prettycards/master/img/CardFrames/" + ext + "/frame_monster.png');}");
    GM_addStyle(".spell.ext_"+ ext +" .cardFrame {background-image: url('https://raw.githubusercontent.com/elytrafae/prettycards/master/img/CardFrames/" + ext + "/frame_spell.png');}");
  }

  GM_addStyle(".card.ext_DDLC .cardBackground {background-image: url('https://raw.githubusercontent.com/elytrafae/prettycards/master/img/CardFrames/DDLC/frame_background.png'); top: 7px; height: 231px;}");
  GM_addStyle("@font-face {font-family: Aller;src: url(https://raw.githubusercontent.com/elytrafae/prettycards/master/fonts/Aller_Rg.ttf);}");
  //https://raw.githubusercontent.com/elytrafae/prettycards/master/fonts/Aller_Rg.ttf
  GM_addStyle(".card.ext_DDLC {font-family: Aller;");
  GM_addStyle(".cardHeader, .cardFooter { background-color: rgb(0, 0, 0, 0); }");

  PrettyCards_plugin.events.on("appendCard()", function(data) {
      var html$ = data.element;
      var card = data.card;
    if (card.fixedId >= customCardsStart) {
      html$.addClass("ext_" + card.extension);
      html$.find(".cardImage").css('background', "url('https://raw.githubusercontent.com/elytrafae/prettycards/master/img/Cards/" + card.extension + "/" + card.image + '.' + card.imageExtension + "') no-repeat");
      if ((card.extension !== "BASE") && (card.extension !== "DELTARUNE")) {
        html$.find('.cardRarity').css('background', 'transparent url(\'https://raw.githubusercontent.com/elytrafae/prettycards/master/img/RarityIcons/' + card.extension + '/' + card.rarity + '.png\') no-repeat');
      };
      var cardNameDiv$ = html$.find('.cardName div');
      var cardDescDiv$ = html$.find('.cardDesc div');

      //cardNameDiv$.css('font-size', getResizedFontSize(cardNameDiv$, 25));
      //cardDescDiv$.css('font-size', getResizedFontSize(cardDescDiv$, 81));
      var tribe_elements = html$.find(".cardTribes").children();
      for (var i=0; i < card.tribes.length; i++) {
        var tribe = card.tribes[i];
        if (bonusTribes.includes(tribe)) {
          tribe_elements[i].src = "https://raw.githubusercontent.com/elytrafae/prettycards/master/img/Tribes/" + tribe + ".png";
        }
      }
    }
  });

  /*function AppendCustomCard(container, card) {
      var html$ = window.appendCard(container, card);
      html$.addClass("ext_" + card.extension);
      html$.find(".cardImage").css('background', "url('https://raw.githubusercontent.com/elytrafae/prettycards/master/img/Cards/" + card.extension + "/" + card.image + '.' + card.imageExtension + "') no-repeat");
      console.log("card extension", card.extension);
      if ((card.extension !== "BASE") && (card.extension !== "DELTARUNE")) {
        html$.find('.cardRarity').css('background', 'transparent url(\'https://raw.githubusercontent.com/elytrafae/prettycards/master/img/RarityIcons/' + card.extension + '_' + card.rarity + '.png\') no-repeat');
      };
  }*/


  var _CustomCards = [
    {
      attack : 1,
      hp : 1,
      maxHp : 1,
      originalAttack : 1,
      originalHp : 1,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart,
      fixedId : customCardsStart,
      typeCard : 0,
      name : "Chibi Sayori",
      image : "Chibi_Sayori",
      cost : 3,
      rarity : "COMMON",
      originalCost : 3,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHIBI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 1,
      hp : 1,
      maxHp : 1,
      originalAttack : 1,
      originalHp : 1,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+1,
      fixedId : customCardsStart+1,
      typeCard : 0,
      name : "Chibi Natsuki",
      image : "Chibi_Natsuki",
      cost : 3,
      rarity : "COMMON",
      originalCost : 3,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHIBI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 1,
      hp : 1,
      maxHp : 1,
      originalAttack : 1,
      originalHp : 1,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+2,
      fixedId : customCardsStart+2,
      typeCard : 0,
      name : "Chibi Yuri",
      image : "Chibi_Yuri",
      cost : 3,
      rarity : "COMMON",
      originalCost : 3,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHIBI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 1,
      hp : 1,
      maxHp : 1,
      originalAttack : 1,
      originalHp : 1,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+3,
      fixedId : customCardsStart+3,
      typeCard : 0,
      name : "Chibi Monika",
      image : "Chibi_Monika",
      cost : 5,
      rarity : "COMMON",
      originalCost : 5,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHIBI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 3,
      hp : 3,
      maxHp : 3,
      originalAttack : 3,
      originalHp : 3,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+4,
      fixedId : customCardsStart+4,
      typeCard : 0,
      name : "Sayori",
      image : "Sayori",
      cost : 4,
      rarity : "EPIC",
      originalCost : 4,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["DOKI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 3,
      hp : 4,
      maxHp : 4,
      originalAttack : 3,
      originalHp : 4,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+5,
      fixedId : customCardsStart+5,
      typeCard : 0,
      name : "Natsuki",
      image : "Natsuki",
      cost : 5,
      rarity : "EPIC",
      originalCost : 5,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["DOKI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+6,
      fixedId : customCardsStart+6,
      typeCard : 1,
      name : "Cupcake",
      image : "Cupcake",
      cost : 2,
      rarity : "GENERATED",
      originalCost : 2,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : [],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 4,
      hp : 3,
      maxHp : 3,
      originalAttack : 4,
      originalHp : 3,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+7,
      fixedId : customCardsStart+7,
      typeCard : 0,
      name : "Yuri",
      image : "Yuri",
      cost : 5,
      rarity : "EPIC",
      originalCost : 5,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["DOKI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 3,
      hp : 5,
      maxHp : 5,
      originalAttack : 3,
      originalHp : 5,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+8,
      fixedId : customCardsStart+8,
      typeCard : 0,
      name : "Monika",
      image : "Monika",
      cost : 5,
      rarity : "EPIC",
      originalCost : 5,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["DOKI"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 3,
      hp : 7,
      maxHp : 7,
      originalAttack : 3,
      originalHp : 7,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : true,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+9,
      fixedId : customCardsStart+9,
      typeCard : 0,
      name : "Protagonist",
      image : "Protagonist",
      cost : 6,
      rarity : "EPIC",
      originalCost : 6,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : [],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 4,
      hp : 6,
      maxHp : 6,
      originalAttack : 4,
      originalHp : 6,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+10,
      fixedId : customCardsStart+10,
      typeCard : 0,
      name : "Just Monika",
      image : "Just_Monika",
      cost : 9,
      rarity : "DETERMINATION",
      originalCost : 9,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : [],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+11,
      fixedId : customCardsStart+11,
      typeCard : 1,
      name : "Sayori.chr",
      image : "SayoriCHR",
      cost : 0,
      rarity : "GENERATED",
      originalCost : 0,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHRSPELL"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+12,
      fixedId : customCardsStart+12,
      typeCard : 1,
      name : "Natsuki.chr",
      image : "NatsukiCHR",
      cost : 0,
      rarity : "GENERATED",
      originalCost : 0,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHRSPELL"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+13,
      fixedId : customCardsStart+13,
      typeCard : 1,
      name : "Yuri.chr",
      image : "YuriCHR",
      cost : 0,
      rarity : "GENERATED",
      originalCost : 0,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHRSPELL"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+14,
      fixedId : customCardsStart+14,
      typeCard : 1,
      name : "Monika.chr",
      image : "MonikaCHR",
      cost : 0,
      rarity : "GENERATED",
      originalCost : 0,
      shiny : false,
      quantity : 1,
      extension : "DDLC",
      tribes : ["CHRSPELL"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 4,
      hp : 6,
      maxHp : 6,
      originalAttack : 4,
      originalHp : 6,
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+15,
      fixedId : customCardsStart+15,
      typeCard : 0,
      name : "Melissa Christmas",
      image : "Melissa_Christmas",
      cost : 6,
      rarity : "LEGENDARY",
      originalCost : 6,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : [],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+16,
      fixedId : customCardsStart+16,
      typeCard : 1,
      name : "Green Potion",
      image : "Green_Potion",
      cost : 3,
      rarity : "GENERATED",
      originalCost : 3,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : ["MELISSAATTACK"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+17,
      fixedId : customCardsStart+17,
      typeCard : 1,
      name : "Red Potion",
      image : "Red_Potion",
      cost : 6,
      rarity : "GENERATED",
      originalCost : 6,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : ["MELISSAATTACK"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 4,
      hp : 3,
      maxHp : 3,
      originalAttack : 4,
      originalHp : 3,
      dodge : 1,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : true,
      charge : false,
      taunt : true,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+18,
      fixedId : customCardsStart+18,
      typeCard : 0,
      name : "Cauldron",
      image : "Cauldron",
      cost : 5,
      rarity : "GENERATED",
      originalCost : 5,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : ["MELISSAATTACK"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+19,
      fixedId : customCardsStart+19,
      typeCard : 1,
      name : "Frogify",
      image : "Frogify",
      cost : 4,
      rarity : "GENERATED",
      originalCost : 4,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : ["MELISSAATTACK"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      attack : 2,
      hp : 2,
      maxHp : 2,
      originalAttack : 2,
      originalHp : 2,
      dodge : 2,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+20,
      fixedId : customCardsStart+20,
      typeCard : 0,
      name : "Hopping Frog",
      image : "Hopping_Frog",
      cost : 1,
      rarity : "GENERATED",
      originalCost : 1,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : [],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+21,
      fixedId : customCardsStart+21,
      typeCard : 1,
      name : "Hat Attack",
      image : "Hat_Attack",
      cost : 6,
      rarity : "GENERATED",
      originalCost : 6,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : ["MELISSAATTACK"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    },
    {
      dodge : 0,
      thorns : 0,
      armor : 0,
      paralyzed : 0,
      silence : false,
      kr : 0,
      cantAttack : false,
      charge : false,
      taunt : false,
      ranged : false,
      invulnerable : false,
      haste : false,
      transparency : false,
      anotherChance : false,
      candy : false,
      id : customCardsStart+22,
      fixedId : customCardsStart+22,
      typeCard : 1,
      name : "Flames Of Envy",
      image : "Flames_Of_Envy",
      cost : 3,
      rarity : "GENERATED",
      originalCost : 3,
      shiny : false,
      quantity : 1,
      extension : "LUNA",
      tribes : ["MELISSAATTACK"],
      selectCards : [],
      ownerId : 0,
      typeSkin: 0,
      imageExtension : "png"
    }
  ];

  PrettyCards_plugin.events.on('CardsLoad', function() {
  	console.log("It worked!");
  	for (var i=0; i < _CustomCards.length; i++) {
  		window.allCards.push(_CustomCards[i]);
      if (_CustomCards[i].rarity !== "GENERATED") {
        var shiny = JSON.parse(JSON.stringify(_CustomCards[i]));
        shiny.shiny = true;
        window.collection.push(_CustomCards[i]);
        window.collection.push(shiny);
        for (var key in window.deckCollections) {
          window.deckCollections[key].push(_CustomCards[i]);
          window.deckCollections[key].push(shiny);
        }
      }
  	}
    console.log("underscript.onPage('Decks')", underscript.onPage("Decks"));
    if (underscript.onPage("Decks")) {
      for (var key in window.deckCollections) {
        deckCollections[key].sort(function (a, b) {
            return compare(a.cost, b.cost) || $.i18n('card-name-' + a.id, 1).localeCompare($.i18n('card-name-' + b.id, 1)) || (a.shiny - b.shiny);
       });
        console.log("Deck Collection", key, deckCollections[key]);
      }
      //refreshDeckList();
      console.log("Decks page insertion complete!");
    }
  });
  console.log("CardsLoad event added!", PrettyCards_plugin.events);


}
